version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    env_file: .env
    ports: 
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
  ian-card:
    build: .
    image: ian-card/ian-card
    ports:
      - '3001:3001'
    environment:
        DB_HOST: postgres
        DB_PORT: 5432
    volumes:
      - ./img:/app/client/build/img
    depends_on:
      - postgres
volumes:
  db: